export type UserRole = 'student' | 'creator' | 'institution_admin' | 'super_admin'
export type Plan = 'free' | 'premium_individual' | 'premium_institution'
export type ContentStatus = 'draft' | 'review' | 'published' | 'archived'
export type ContentType = 'text' | 'video' | 'quiz' | 'code'
export type Language = 'pt-BR' | 'en'
export type QuestStatus = 'active' | 'completed' | 'failed'
export type InstitutionRole = 'admin' | 'student'
export type XPSourceType =
  | 'lesson_complete'
  | 'streak_bonus'
  | 'badge_earned'
  | 'quest_complete'
  | 'daily_login'
export type Theme = 'light' | 'dark' | 'high-contrast'
export type FontSize = 'normal' | 'large' | 'xlarge'
export type NotificationType =
  | 'streak_reminder'
  | 'badge_earned'
  | 'level_up'
  | 'institution_invite'
  | 'quest_completed'
export type AvatarItemType = 'hat' | 'clothing' | 'accessory' | 'background'
